name: Mackay Churches Together
url: "http://davidjohnmiller.github.io/mackaychurchestogether"
timezone: Australia/Brisbane
branch: gh-pages

weekdays:
  - "Monday"
  - "Tuesday"
  - "Wednesday"
  - "Thursday"
  - "Friday"
  - "Saturday"
  - "Sunday"

collections:
  churches:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "churches"
    values:
      layout: "church"
      denomination: "Other"

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

sass:
  style: compressed